spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MDFinance accounts related prod APIs "
  contactDetails:
    name: "Om Davra - Developer"
    email: "om@MDFinance.com"
  onCallSupport:
    - (777) 777-1234
    - (777) 523-1345