build:
  version: "3.0"

accounts:
  message: "Welcome to MDFinance accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@md.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384