build:
  version: "3.0"

loans:
  message: "Welcome to MDFinance loans related prod APIs "
  contactDetails:
    name: "Pelicans Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956