server:
    port: 8080
spring:
    application:
        name: "accounts"
    profiles:
        active: "prod"
    datasource:
        url: jdbc:mysql://localhost:3306/accountsdb
        username: root
        password: root
    jpa:
        show-sql: true
    sql:
        init:
            mode: always
    config:
        import: "optional:configserver:http://localhost:8071/"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true

    info: # This is to enable the info endpoint
        env:
            enabled: true

endpoints:
    shutdown:
        enabled: true

eureka:
    instance:
        preferIpAddress: true # This is to get the IP address of the service registered with Eureka
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/

info:
    app:
        name: "accounts"
        description: "MDFinance Accounts Microservice"
        version: "1.0"

logging:
    level:
        com:
            mdfinance:
                accounts:
                    controller: DEBUG
                    service: DEBUG
                    repository: DEBUG