spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient: # This configuration is global and will be applied to all the services passing through the gateway.
        connect-timeout: 1000
        response-timeout: 20s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          # Can be found from the keycloak realm - http://localhost:7080/realms/master/.well-known/openid-configuration
          # Resource server will use this URI to fetch the public keys and verify the JWT signature.
          # In our case, Gateway server will act as a resource server.
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info: # This is to enable the info endpoint
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "MDFinance Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      MDFinance:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # On how many requests the circuit breaker has \n
      # to monitor before it tries to change the status from closed to open
      permittedNumberOfCallsInHalfOpenState: 2 # only allow these many requests in half-open state
      failureRateThreshold: 50 # if we have a positive response from 50% of the request, then the state will moved from closed to open.
      waitDurationInOpenState: 10000 # wait time of 10-second in Open state.