services:
  accounts:
    image: "maulikdavra/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - MDFinance
  loans:
    image: "maulikdavra/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - MDFinance
  cards:
    image: "maulikdavra/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - MDFinance
networks:
  MDFinance:
    driver: "bridge"