spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/Maulikdavra/MDFinance-config"
          default-label: main
          timeout: 5
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info: # This is to enable the info endpoint
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      MDFinance:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

encrypt:
  key: "99581101MD611019958"


server:
  port: 8071