package com.md.spring_security_for_mdfinance.respository;

import com.md.spring_security_for_mdfinance.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * @Author Maulik Davra
 * @Created on July 5th 2024
 * <br/>
 * <br/>CustomerRepository is a repository class which is used to interact with the database.
 * <br/>It is used to perform CRUD operations on the customer entity.
 */
@Repository
public interface CustomerRepository extends JpaRepository<Customer, Integer> {

    /**
     * This method is used to find the customer by name. (it's an autogenerated method)
     * @param name - of the customer
     * @return - customer details
     */
    Optional<Customer> findByName(String name);
}
