server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints: # This is to enable all the endpoints
    web:
      exposure:
        include: "*"
  endpoint: # This is to enable the shutdown endpoint
    shutdown:
      enabled: true
  info: # This is to enable the info endpoint
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # This is to get the IP address of the service registered with Eureka
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "MDFinance Loans Microservice"
    version: "1.0"